#!/usr/bin/env bash
# chair can save your server account (saved locally ~ / .chair.rc), he can facilitate some of the commands the server account needs

defaultDrive='_chairSsh'
defaultConfigPath=~/.chair.rc
chairVersion='5.2.0'
chairLastUpdateTime='2018-04-07'

function _chairShowVersion() {
	echo "
      __                            
     /\\ \\                __         
  ___\\ \\ \\___      __   /\\_\\  _ __  
 /'___\\ \\  _ \`\\  /\'__\`\\ \\/\\ \\/\\\`'__\\
/\\ \\__/\\ \\ \\ \\ \\/\\ \\L\\.\\_\\ \\ \\ \\ \\/ 
\\ \\____\\\\ \\_\\ \\_\\ \\__/.\\_\\\\ \\_\\ \\_\\ 
 \\/____/ \\/_/\\/_/\\/__/\\/_/ \\/_/\\/_/ 
                                    
chair version ${chairVersion} ${chairLastUpdateTime}
" 
}

function _chairHelp() {
	echo "USAGE: chair add [-n ALIAS] [-u USER] [-p PROT| -c cipher/password]"
	echo "       chair delete ALIAS"
	echo "       chair ALIAS"
	echo "       chair scp ALIAS"
	echo "       chair [scp | ] [-f alias fortress] ALIAS"
	echo "       chair version"
	echo "       chair find ALIAS"
}

# initialization
if [[ ! -e ${defaultConfigPath} ]]; then
	say hello chair
	_chairShowVersion
	touch ${defaultConfigPath}
	echo "starting initialization..."
	echo "#chair.rc for chair." > ${defaultConfigPath}
fi

function _chairList() {
	varList=$(cat ~/.chair.rc | grep "# \[" | cut -d'[' -f 2 | cut -d']' -f 1)
	echo -e "ALIAS \t\t USER \t IP \t\t\t PORT"
	for var in $varList
	do
		_getConfigVar $var false
    	echo -e "${var} \t ${!FREEZECOMBO_USER} \t ${!FREEZECOMBO_IP}      \t ${!FREEZECOMBO_PORT}"
	done
}

function _chairAdd() {
	# getopts parameter analysis
	while getopts "n:u:i:p:c:" arg
	do
        case $arg in
	        n) chairName="${OPTARG}" ;;
	        u) chairUser="${OPTARG}" ;;
	        i) chairIp="${OPTARG}" ;;
			p) chairPort="${OPTARG}" ;;
			c) chairCipher="${OPTARG}" ;;
	        ?) echo "Invalid option: -$OPTARG"; exit 0 ;;
        esac
	done
	echo "# [${chairName}]" >> ${defaultConfigPath}
	echo "${chairName}_user='${chairUser}'" >> ${defaultConfigPath}
	echo "${chairName}_ip='${chairIp}'" >> ${defaultConfigPath}
	echo "${chairName}_port='${chairPort:-22}'" >> ${defaultConfigPath}
	echo "${chairName}_cipher='${chairCipher}'" >> ${defaultConfigPath}
}

function _chairFind() {
	_getConfigVar $1 false
	echo -e "\033[4m ${1} \033[0m \033[32;49;1m [User] \033[39;49;0m ${!FREEZECOMBO_USER} \033[32;49;1m [IP] \033[39;49;0m ${!FREEZECOMBO_IP} \033[32;49;1m [Port] \033[39;49;0m ${!FREEZECOMBO_PORT} \033[32;49;1m [Password/Cipher] \033[39;49;0m ${!FREEZECOMBO_CIPHER}"
}

function _chairDelete() {
	if [[ -z ${1} ]]; then return 1; fi
	sed -i "" "/\[${1}\]/d" ${defaultConfigPath}
	sed -i "" "/${1}_user/d" ${defaultConfigPath}
	sed -i "" "/${1}_ip/d" ${defaultConfigPath}
	sed -i "" "/${1}_port/d" ${defaultConfigPath}
	sed -i "" "/${1}_cipher/d" ${defaultConfigPath}
}

function _getConfigVar() {
	source ${defaultConfigPath}
	FREEZECOMBO_USER=$1_user
	FREEZECOMBO_IP=$1_ip
	FREEZECOMBO_PORT=$1_port
	FREEZECOMBO_CIPHER=$1_cipher
	
	if [[ ! -z ${!FREEZECOMBO_CIPHER} && ${2} != false ]]; then
		echo "${!FREEZECOMBO_CIPHER}" | pbcopy;echo -e "The cipher has been copied to the clipboard, directly \033[49 CCOMMAND + V \033[0m paster."
	fi
}

function _chairSsh() {
	# getopts parameter analysis
    while getopts "f:" arg
    do
        case $arg in
            f) chairFortress="${OPTARG}" ;;
            ?) echo "Invalid option: -$OPTARG"; exit 0 ;;
        esac
    done

	if [[ ! -z $chairFortress ]];then
		_getConfigVar $chairFortress false
		FREEZECOMBO_FORTRESS_PORT=${FREEZECOMBO_PORT}
		FREEZECOMBO_FORTRESS_USER=${FREEZECOMBO_USER}
		FREEZECOMBO_FORTRESS_IP=${FREEZECOMBO_IP}
		FREEZECOMBO_FORTRESS_CIPHER=${FREEZECOMBO_CIPHER}
		
		_getConfigVar $3
		ssh -t -p ${!FREEZECOMBO_FORTRESS_PORT} ${!FREEZECOMBO_FORTRESS_USER}@${!FREEZECOMBO_FORTRESS_IP} "ssh -p ${!FREEZECOMBO_PORT} ${!FREEZECOMBO_USER}@${!FREEZECOMBO_IP}"
		exit 0
	fi

	_getConfigVar $1
	ssh -p ${!FREEZECOMBO_PORT} ${!FREEZECOMBO_USER}@${!FREEZECOMBO_IP}
}

function _chairScp() {
	# getopts parameter analysis
    while getopts "f:" arg
    do
        case $arg in
            f) chairFortress="${OPTARG}" ;;
            ?) echo "Invalid option: -$OPTARG"; exit 0 ;;
        esac
    done

	if [[ ! -z $chairFortress ]];then
		_getConfigVar $chairFortress false
        FREEZECOMBO_FORTRESS_PORT=${FREEZECOMBO_PORT}
        FREEZECOMBO_FORTRESS_USER=${FREEZECOMBO_USER}
        FREEZECOMBO_FORTRESS_IP=${FREEZECOMBO_IP}
        FREEZECOMBO_FORTRESS_CIPHER=${FREEZECOMBO_CIPHER}

        chairAddressIn3=${3#*:}
		chairNameIn3=${3%:*}
		chairAddressIn4=${4#*:}
		chairNameIn4=${4%:*}
		if [[ ${chairAddressIn3} != ${chairNameIn3} ]]; then
			_getConfigVar ${chairNameIn3}
			let i=${#chairAddressIn3}-1
			if [[ ${chairAddressIn3:$i:1} == '/' ]];then
				chairAddressIn3=${chairAddressIn3%/}
			fi
			ssh -p ${!FREEZECOMBO_FORTRESS_PORT} ${!FREEZECOMBO_FORTRESS_USER}@${!FREEZECOMBO_FORTRESS_IP} "scp -r -P ${!FREEZECOMBO_PORT} ${!FREEZECOMBO_USER}@${!FREEZECOMBO_IP}:${chairAddressIn3} /tmp/"
			scp -r -P ${!FREEZECOMBO_FORTRESS_PORT} ${!FREEZECOMBO_FORTRESS_USER}@${!FREEZECOMBO_FORTRESS_IP}:/tmp/${chairAddressIn3##*/} $4
		elif [[ ${chairAddressIn4} != ${chairNameIn4} ]]; then
			_getConfigVar ${chairNameIn4}
			scp -r -P ${!FREEZECOMBO_FORTRESS_PORT} $3 ${!FREEZECOMBO_FORTRESS_USER}@${!FREEZECOMBO_FORTRESS_IP}:/tmp/
			ssh -p ${!FREEZECOMBO_FORTRESS_PORT} ${!FREEZECOMBO_FORTRESS_USER}@${!FREEZECOMBO_FORTRESS_IP} "scp -P ${!FREEZECOMBO_PORT} /tmp/${3##*/} ${!FREEZECOMBO_USER}@${!FREEZECOMBO_IP}:${chairAddressIn4}"
        else
        	exit 1
        fi
        
        return 0
	fi

	chairAddressIn1=${1#*:}
	chairNameIn1=${1%:*}
	chairAddressIn2=${2#*:}
	chairNameIn2=${2%:*}

	if [[ ${chairAddressIn1} != ${chairNameIn1} ]]; then
		_getConfigVar ${chairNameIn1}
		scp -r -P ${!FREEZECOMBO_PORT} ${!FREEZECOMBO_USER}@${!FREEZECOMBO_IP}:${chairAddressIn1} $2
	elif [[ ${chairAddressIn2} != ${chairNameIn2} ]]; then
		_getConfigVar ${chairNameIn2}
		scp -r -P ${!FREEZECOMBO_PORT} $1 ${!FREEZECOMBO_USER}@${!FREEZECOMBO_IP}:${chairAddressIn2}
	else
		exit 1
	fi
}

case $1 in
	add)
		_chairAdd $(echo $* | awk '$1="";1')
	;;
	delete)
		_chairDelete $(echo $* | awk '$1="";1')
	;;
	version)
		_chairShowVersion	
	;;
	find)
		_chairFind $2
	;;
	completion)
		complete -W "$(cat ~/.chair.rc | grep "# \[" | cut -d'[' -f 2 | cut -d']' -f 1)" chair
	;;
	help)
		_chairHelp
	;;
	scp)
		_chairScp $(echo $* | awk '$1="";1')
	;;
	list)
		_chairList
	;;
	*)
		${defaultDrive} $*
	;;
esac
