#!/usr/bin/env bash
# fcb BASED ON MacOS.

# env
defaultDrive='_freezecomboSsh'
defaultConfigPath=~/.freezecombo.rc
freezecomboVersion='4.0.0'
freezecomboLastUpdateTime='2017-11-25 19:55'

function _freezecomboShowVersion() {
	echo "
  __                                           _           
 / _|_ __ ___  ___ _______  ___ ___  _ __ ___ | |__   ___  
| |_| '__/ _ \\/ _ \\_  / _ \\/ __/ _ \\| '_ \` _ \\| '_ \\ / _ \\ 
|  _| | |  __/  __// /  __/ (_| (_) | | | | | | |_) | (_) |
|_| |_|  \___|\___/___\___|\___\___/|_| |_| |_|_.__/ \___/ 
                                                           
fcb version ${freezecomboVersion} ${freezecomboLastUpdateTime}
" 
}

function _freezecomboHelp() {
	echo "Usage: fcb add [-n name] [-u user] [-p port | -c cipher/password]"
	echo "       fcb delete \`name\`"
	echo "       fcb \`name\`"
	echo "       fcb scp \`name\`"
	echo "       fcb version"
	echo "       fcb find \`name\`"
}

# initialization
if [[ ! -e ${defaultConfigPath} ]]; then
	say hello freezecombo
	_freezecomboShowVersion
	touch ${defaultConfigPath}
	echo "starting initialization..."
	echo "#freezecombo.rc for fcb." > ${defaultConfigPath}
fi

function _freezecomboAdd() {
	# getopts parameter analysis
	while getopts "n:u:i:p:c:" arg
	do
        case $arg in
	        n) freezecomboName="${OPTARG}" ;;
	        u) freezecomboUser="${OPTARG}" ;;
	        i) freezecomboIp="${OPTARG}" ;;
			p) freezecomboPort="${OPTARG}" ;;
			c) freezecomboCipher="${OPTARG}" ;;
	        ?) echo "Invalid option: -$OPTARG"; exit 0 ;;
        esac
	done
	echo "# [${freezecomboName}]" >> ${defaultConfigPath}
	echo "${freezecomboName}_user='${freezecomboUser}'" >> ${defaultConfigPath}
	echo "${freezecomboName}_ip='${freezecomboIp}'" >> ${defaultConfigPath}
	echo "${freezecomboName}_port='${freezecomboPort:-22}'" >> ${defaultConfigPath}
	echo "${freezecomboName}_cipher='${freezecomboCipher}'" >> ${defaultConfigPath}
}

function _freezecomboFind() {
	_getConfigVar $1 false
	echo -e "\033[4m ${1} \033[0m \033[32;49;1m [User] \033[39;49;0m ${!FREEZECOMBO_USER} \033[32;49;1m [IP] \033[39;49;0m ${!FREEZECOMBO_IP} \033[32;49;1m [Port] \033[39;49;0m ${!FREEZECOMBO_PORT} \033[32;49;1m [Password/Cipher] \033[39;49;0m ${!FREEZECOMBO_CIPHER}"
}

function _freezecomboDelete() {
	if [[ -z ${1} ]]; then return 1; fi
	sed -i "" "/\[${1}\]/d" ${defaultConfigPath}
	sed -i "" "/${1}_user/d" ${defaultConfigPath}
	sed -i "" "/${1}_ip/d" ${defaultConfigPath}
	sed -i "" "/${1}_port/d" ${defaultConfigPath}
	sed -i "" "/${1}_cipher/d" ${defaultConfigPath}
}

function _getConfigVar() {
	source ${defaultConfigPath}
	FREEZECOMBO_USER=$1_user
	FREEZECOMBO_IP=$1_ip
	FREEZECOMBO_PORT=$1_port
	FREEZECOMBO_CIPHER=$1_cipher
	
	if [[ ! -z ${!FREEZECOMBO_CIPHER} && ${2} != false ]]; then
		echo "${!FREEZECOMBO_CIPHER}" | pbcopy;echo -e "The cipher has been copied to the clipboard, directly \033[49;30;5m COMMAND + V \033[0m paster."
	fi
}

function _freezecomboSsh() {
	_getConfigVar $1
	ssh -p ${!FREEZECOMBO_PORT} ${!FREEZECOMBO_USER}@${!FREEZECOMBO_IP}
}

function _freezecomboScp() {
	fcbAddressIn2=${2#*:}
	fcbNameIn2=${2%:*}
	fcbAddressIn3=${3#*:}
	fcbNameIn3=${3%:*}

	if [[ ${fcbAddressIn2} != ${fcbNameIn2} ]]; then
		_getConfigVar ${fcbNameIn2}
		scp -r -P ${!FREEZECOMBO_PORT} ${!FREEZECOMBO_USER}@${!FREEZECOMBO_IP}:${fcbAddressIn2} $3
	elif [[ ${fcbAddressIn3} != ${fcbNameIn3} ]]; then
		_getConfigVar ${fcbNameIn3}
		scp -r -P ${!FREEZECOMBO_PORT} $2 ${!FREEZECOMBO_USER}@${!FREEZECOMBO_IP}:${fcbAddressIn3}
	else
		exit 1
	fi
}

case $1 in
	add)
		_freezecomboAdd $(echo $* | awk '$1="";1')
	;;
	delete)
		_freezecomboDelete $(echo $* | awk '$1="";1')
	;;
	version)
		_freezecomboShowVersion	
	;;
	find)
		_freezecomboFind $2
	;;
	completion)
		complete -W "$(cat ~/.freezecombo.rc | grep "# \[" | cut -d'[' -f 2 | cut -d']' -f 1)" fcb
	;;
	help)
		_freezecomboHelp
	;;
	scp)
		_freezecomboScp $*
	;;
	*)
		${defaultDrive} $*
	;;
esac
