#!/usr/bin/env bash
# fcb BASED ON MacOS.
set -x

# env
defaultDrive='_freezecomboSsh'
defaultConfigPath=~/.freezecombo.rc
freezecomboVersion='5.1.2'
freezecomboLastUpdateTime='2017-12-12 10:42'

function _freezecomboShowVersion() {
	echo "
  __                                           _           
 / _|_ __ ___  ___ _______  ___ ___  _ __ ___ | |__   ___  
| |_| '__/ _ \\/ _ \\_  / _ \\/ __/ _ \\| '_ \` _ \\| '_ \\ / _ \\ 
|  _| | |  __/  __// /  __/ (_| (_) | | | | | | |_) | (_) |
|_| |_|  \___|\___/___\___|\___\___/|_| |_| |_|_.__/ \___/ 
                                                           
fcb version ${freezecomboVersion} ${freezecomboLastUpdateTime}
" 
}

function _freezecomboHelp() {
	echo "USAGE: fcb add [-n ALIAS] [-u USER] [-p PROT| -c cipher/password]"
	echo "       fcb delete ALIAS"
	echo "       fcb ALIAS"
	echo "       fcb scp ALIAS"
	echo "       fcb [scp | ] [-f alias fortress] ALIAS"
	echo "       fcb version"
	echo "       fcb find ALIAS"
}

# initialization
if [[ ! -e ${defaultConfigPath} ]]; then
	say hello freezecombo
	_freezecomboShowVersion
	touch ${defaultConfigPath}
	echo "starting initialization..."
	echo "#freezecombo.rc for fcb." > ${defaultConfigPath}
fi

function _freezecomboList() {
	varList=$(cat ~/.freezecombo.rc | grep "# \[" | cut -d'[' -f 2 | cut -d']' -f 1)
	echo -e "ALIAS \t\t USER \t IP \t\t\t PORT"
	for var in $varList
	do
		_getConfigVar $var false
    	echo -e "${var} \t ${!FREEZECOMBO_USER} \t ${!FREEZECOMBO_IP}      \t ${!FREEZECOMBO_PORT}"
	done
}

function _freezecomboAdd() {
	# getopts parameter analysis
	while getopts "n:u:i:p:c:" arg
	do
        case $arg in
	        n) freezecomboName="${OPTARG}" ;;
	        u) freezecomboUser="${OPTARG}" ;;
	        i) freezecomboIp="${OPTARG}" ;;
			p) freezecomboPort="${OPTARG}" ;;
			c) freezecomboCipher="${OPTARG}" ;;
	        ?) echo "Invalid option: -$OPTARG"; exit 0 ;;
        esac
	done
	echo "# [${freezecomboName}]" >> ${defaultConfigPath}
	echo "${freezecomboName}_user='${freezecomboUser}'" >> ${defaultConfigPath}
	echo "${freezecomboName}_ip='${freezecomboIp}'" >> ${defaultConfigPath}
	echo "${freezecomboName}_port='${freezecomboPort:-22}'" >> ${defaultConfigPath}
	echo "${freezecomboName}_cipher='${freezecomboCipher}'" >> ${defaultConfigPath}
}

function _freezecomboFind() {
	_getConfigVar $1 false
	echo -e "\033[4m ${1} \033[0m \033[32;49;1m [User] \033[39;49;0m ${!FREEZECOMBO_USER} \033[32;49;1m [IP] \033[39;49;0m ${!FREEZECOMBO_IP} \033[32;49;1m [Port] \033[39;49;0m ${!FREEZECOMBO_PORT} \033[32;49;1m [Password/Cipher] \033[39;49;0m ${!FREEZECOMBO_CIPHER}"
}

function _freezecomboDelete() {
	if [[ -z ${1} ]]; then return 1; fi
	sed -i "" "/\[${1}\]/d" ${defaultConfigPath}
	sed -i "" "/${1}_user/d" ${defaultConfigPath}
	sed -i "" "/${1}_ip/d" ${defaultConfigPath}
	sed -i "" "/${1}_port/d" ${defaultConfigPath}
	sed -i "" "/${1}_cipher/d" ${defaultConfigPath}
}

function _getConfigVar() {
	source ${defaultConfigPath}
	FREEZECOMBO_USER=$1_user
	FREEZECOMBO_IP=$1_ip
	FREEZECOMBO_PORT=$1_port
	FREEZECOMBO_CIPHER=$1_cipher
	
	if [[ ! -z ${!FREEZECOMBO_CIPHER} && ${2} != false ]]; then
		echo "${!FREEZECOMBO_CIPHER}" | pbcopy;echo -e "The cipher has been copied to the clipboard, directly \033[49 CCOMMAND + V \033[0m paster."
	fi
}

function _freezecomboSsh() {
	# getopts parameter analysis
    while getopts "f:" arg
    do
        case $arg in
            f) freezecomboFortress="${OPTARG}" ;;
            ?) echo "Invalid option: -$OPTARG"; exit 0 ;;
        esac
    done

	if [[ ! -z $freezecomboFortress ]];then
		_getConfigVar $freezecomboFortress false
		FREEZECOMBO_FORTRESS_PORT=${FREEZECOMBO_PORT}
		FREEZECOMBO_FORTRESS_USER=${FREEZECOMBO_USER}
		FREEZECOMBO_FORTRESS_IP=${FREEZECOMBO_IP}
		FREEZECOMBO_FORTRESS_CIPHER=${FREEZECOMBO_CIPHER}
		
		_getConfigVar $3
		ssh -t -p ${!FREEZECOMBO_FORTRESS_PORT} ${!FREEZECOMBO_FORTRESS_USER}@${!FREEZECOMBO_FORTRESS_IP} "ssh -p ${!FREEZECOMBO_PORT} ${!FREEZECOMBO_USER}@${!FREEZECOMBO_IP}"
		exit 0
	fi

	_getConfigVar $1
	ssh -p ${!FREEZECOMBO_PORT} ${!FREEZECOMBO_USER}@${!FREEZECOMBO_IP}
}

function _freezecomboScp() {
	# getopts parameter analysis
    while getopts "f:" arg
    do
        case $arg in
            f) freezecomboFortress="${OPTARG}" ;;
            ?) echo "Invalid option: -$OPTARG"; exit 0 ;;
        esac
    done

	if [[ ! -z $freezecomboFortress ]];then
		_getConfigVar $freezecomboFortress false
        FREEZECOMBO_FORTRESS_PORT=${FREEZECOMBO_PORT}
        FREEZECOMBO_FORTRESS_USER=${FREEZECOMBO_USER}
        FREEZECOMBO_FORTRESS_IP=${FREEZECOMBO_IP}
        FREEZECOMBO_FORTRESS_CIPHER=${FREEZECOMBO_CIPHER}

        fcbAddressIn3=${3#*:}
		fcbNameIn3=${3%:*}
		fcbAddressIn4=${4#*:}
		fcbNameIn4=${4%:*}
		if [[ ${fcbAddressIn3} != ${fcbNameIn3} ]]; then
			_getConfigVar ${fcbNameIn3}
			let i=${#fcbAddressIn3}-1
			if [[ ${fcbAddressIn3:$i:1} == '/' ]];then
				fcbAddressIn3=${fcbAddressIn3%/}
			fi
			ssh -p ${!FREEZECOMBO_FORTRESS_PORT} ${!FREEZECOMBO_FORTRESS_USER}@${!FREEZECOMBO_FORTRESS_IP} "scp -r -P ${!FREEZECOMBO_PORT} ${!FREEZECOMBO_USER}@${!FREEZECOMBO_IP}:${fcbAddressIn3} /tmp/"
			scp -r -P ${!FREEZECOMBO_FORTRESS_PORT} ${!FREEZECOMBO_FORTRESS_USER}@${!FREEZECOMBO_FORTRESS_IP}:/tmp/${fcbAddressIn3##*/} $4
		elif [[ ${fcbAddressIn4} != ${fcbNameIn4} ]]; then
			_getConfigVar ${fcbNameIn4}
			scp -r -P ${!FREEZECOMBO_FORTRESS_PORT} $3 ${!FREEZECOMBO_FORTRESS_USER}@${!FREEZECOMBO_FORTRESS_IP}:/tmp/
			ssh -p ${!FREEZECOMBO_FORTRESS_PORT} ${!FREEZECOMBO_FORTRESS_USER}@${!FREEZECOMBO_FORTRESS_IP} "scp -P ${!FREEZECOMBO_PORT} /tmp/${3##*/} ${!FREEZECOMBO_USER}@${!FREEZECOMBO_IP}:${fcbAddressIn4}"
        else
        	exit 1
        fi
        
        return 0
	fi

	fcbAddressIn1=${1#*:}
	fcbNameIn1=${1%:*}
	fcbAddressIn2=${2#*:}
	fcbNameIn2=${2%:*}

	if [[ ${fcbAddressIn1} != ${fcbNameIn1} ]]; then
		_getConfigVar ${fcbNameIn1}
		scp -r -P ${!FREEZECOMBO_PORT} ${!FREEZECOMBO_USER}@${!FREEZECOMBO_IP}:${fcbAddressIn1} $2
	elif [[ ${fcbAddressIn2} != ${fcbNameIn2} ]]; then
		_getConfigVar ${fcbNameIn2}
		scp -r -P ${!FREEZECOMBO_PORT} $1 ${!FREEZECOMBO_USER}@${!FREEZECOMBO_IP}:${fcbAddressIn2}
	else
		exit 1
	fi
}

case $1 in
	add)
		_freezecomboAdd $(echo $* | awk '$1="";1')
	;;
	delete)
		_freezecomboDelete $(echo $* | awk '$1="";1')
	;;
	version)
		_freezecomboShowVersion	
	;;
	find)
		_freezecomboFind $2
	;;
	completion)
		complete -W "$(cat ~/.freezecombo.rc | grep "# \[" | cut -d'[' -f 2 | cut -d']' -f 1)" fcb
	;;
	help)
		_freezecomboHelp
	;;
	scp)
		_freezecomboScp $(echo $* | awk '$1="";1')
	;;
	list)
		_freezecomboList
	;;
	*)
		${defaultDrive} $*
	;;
esac
