#!/usr/bin/env bash
#
# Use script to manage your small pieces of command, so that your command configuration modular,
# skilled use of shell orders will have a better performance, efficient, safe, easier to use.
# for MacOS/*unix
#
# @author <ge2x3k2@gmail.com>
# @time 2017-06-29
# @version 1.3

#set -x
# Read the command configuration file
config_path='/etc/pppp/pppp.conf'

# There must be a parameter
if [[ $# == 0 ]]; then echo -e "failed: because there is no parameter that leads to failure.\nuse 'pppp -l' View the available parameters";exit 1; fi

# The configuration dir must exist
if [[ ! -d ${config_path%%pppp.conf} ]]; then
	echo "initialization: mkdir -vp ${config_path%%pppp.conf}"
	mkdir -vp ${config_path%%pppp.conf}
fi
# The configuration file must exist
if [[ ! -f ${config_path} ]]; then
	echo "initialization: touch ${config_path}"
	touch ${config_path}
	echo "#pppp.conf" >> ${config_path}
	echo "" >> ${config_path}
	echo "Initialized successfully."
fi

# Read
source $config_path

# help
_getHelp () {
	echo "Usage:  pppp -s execute the save operation"
	echo "	pppp -n name"
	echo "	pppp -e name the call to the command"
	echo "	pppp -a turn on safe mode"
	echo "	pppp -u account, present is displayed"
	echo "	pppp -p password, present is displayed"
	echo "	pppp -d delete an existing command"
	echo "	pppp -l show the configuration file"
	echo "	pppp -v view the version"
	echo "	pppp -f find for related configurations based on clues(-f'clues')"
	echo ""
	echo "  	directly called the command to execute the formation, specified in the -e"
	echo ""
	echo "Example: pppp -sn'name' -e'exec' -u'username' -p'password'"
}

# getopts parameter analysis
while getopts "slhvabd:u:n:p:e:f:" arg
do
        case $arg in
            # Execute the save operation
            s) pppp_save=1 ;;
	    # name
            n) pppp_name="${OPTARG}" ;;
      	    # Name the call to the command
    	    e) pppp_exec="${OPTARG}" ;;
	    # turn on safe mode
            a) pppp_safe=1 ;;
            # Account, present is displayed
            u) pppp_user="${OPTARG}" ;;
            # Password, present is displayed
            p) pppp_password="${OPTARG}" ;;
	    d) pppp_delete="${OPTARG}" ;;
	    # alias
	    b) ;;
	    # find
	    f) pppp_find="${OPTARG}" ;;
	    # list config
	    l) less ${config_path}; exit 0 ;;
	    # show version
	    v) echo "version: 1.3"; exit 0 ;;
	    # show help docs
	    h) _getHelp; exit 0 ;;
            ?) echo "unkonw argument"; exit 1 ;;
        esac
done

# elete an existing command
_delete () {
	if [[ -z ${pppp_delete} ]]; then return 0; fi
	sed -i "" "/\[${pppp_delete}\]/d" ${config_path}
	sed -i "" "/${pppp_delete}_exec/d" ${config_path}
	sed -i "" "/${pppp_delete}_user/d" ${config_path}
	sed -i "" "/${pppp_delete}_password/d" ${config_path}
	sed -i "" "/${pppp_delete}_safe/d" ${config_path}
	exit 0
}

# find
_find () {
	sed -n "/${pppp_find}/p" ${config_path}
	exit 0
}


# Save the operation of the command
_filling_file () {
	if [[ -z ${pppp_save} ]]; then	return 0; fi

	if [[ -z ${pppp_name} || -z ${pppp_exec} ]]; then echo -e "failed: 'pppp -s' requires at least '-e' and '-n' two parameters\nSee 'pppp -h'";exit 1; fi

	echo "# [${pppp_name}]" >> ${config_path}
	echo "${pppp_name}_exec='${pppp_exec}'" >> ${config_path}

	if [[ ! -z ${pppp_user} ]]; then echo "${pppp_name}_user='${pppp_user}'" >> ${config_path}; fi

	if [[ ! -z ${pppp_password} ]]; then echo "${pppp_name}_password='${pppp_password}'" >> ${config_path}; fi

	if [[ ! -z ${pppp_safe} ]]; then echo "${pppp_name}_safe=1" >> ${config_path}; fi

	echo "" >> ${config_path}

	echo "..."
	echo "create success."

	exit 0
}

# Safe mode
_safe () {
	read -n 1 -p 'the above statement will be executed, please approve[y/n]: ' state
	echo ""
	if [[ $state != 'y' ]]; then
		echo "bye.."
		exit 0
	fi
	echo -e "info: ${!eeec}"
}

# Execute named commands
_eeec () {
	eeec=$1_exec
	if [[ -z ${!eeec} ]]; then echo -e "failed: there is no viable command for this parameter\nuse the 'pppp -sn -e' command to add";exit 1; fi

	local user=$1_user
	local password=$1_password
	local safe=$1_safe

	if [[ ${!safe} == '1' ]]; then _safe; fi

	if [[ ! -z ${!user} ]]; then echo -e "account:";echo "     ${!user}"; echo ""; fi
	if [[ ! -z ${!password} ]]; then echo "${!password}" | pbcopy; echo "The password has been copied to the clipboard, directly 'CTRL V' paste."; fi

	${!eeec}
	return 0
}

_filling_file

_delete

if [[ ! -z ${pppp_find} ]]; then
	_find
fi

_eeec $1
exit 0

# End of file for pppp
